apiVersion: apps/v1
kind: Deployment
metadata:
  name: mh-th-app
  namespace: mh-th-app  
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mh-th-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mh-th-app
    spec:
      containers:
        - name: app
          image: my-totally-real-repo.io:this-will-be-replaced
          ports:
            - name: http
              containerPort: 80