apiVersion: v1
kind: Service
metadata:
  name: mh-th-app

# this wouldnt work on a real cluster, you'd have some kind of controller set up to manage this
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mh-th-app
  ports:
    - name: https
      port: 443
      targetPort: http
      protocol: TCP